import postgres from 'postgres';

const sql = postgres(process.env.POSTGRES_URL!, { ssl: 'require' });

async function createUsers() {
    await sql`
        CREATE TABLE IF NOT EXISTS users
        (
            id       UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
            name     VARCHAR(100) NOT NULL,
            email    VARCHAR(100) NOT NULL UNIQUE,
            password VARCHAR(100) NOT NULL
        );
    `;
}

async function createCertificates() {
    await sql`
        CREATE TABLE IF NOT EXISTS certificate
        (
            id      UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
            user_id UUID         NOT NULL,
            label   VARCHAR(100) NOT NULL,
            date    DATE         NOT NULL,

            CONSTRAINT fk_certificate_user
                FOREIGN KEY (user_id)
                    REFERENCES users (id)
        );
    `;
}

async function createProjects() {
    await sql`
        CREATE TABLE IF NOT EXISTS project
        (
            id          UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
            user_id     UUID         NOT NULL,
            label       VARCHAR(100) NOT NULL,
            description TEXT,
            start_date  DATE         NOT NULL,
            end_date    DATE,

            CONSTRAINT fk_project_user
                FOREIGN KEY (user_id)
                    REFERENCES users (id)
        );
    `;
}

async function createDevCategories() {
    await sql`
        CREATE TABLE IF NOT EXISTS dev_category
        (
            id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            label VARCHAR(100) NOT NULL
        );
    `;
}

async function createFrameworks() {
    await sql`
        CREATE TABLE IF NOT EXISTS framework
        (
            id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            label VARCHAR(100) NOT NULL UNIQUE
        );
    `;
}

async function createLanguages() {
    await sql`
        CREATE TABLE IF NOT EXISTS language
        (
            id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            label VARCHAR(100) NOT NULL UNIQUE
        );
    `;
}

async function createLearnsubjects() {
    await sql`
        CREATE TABLE IF NOT EXISTS learnsubject
        (
            id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            label VARCHAR(100) NOT NULL UNIQUE
        );
    `;
}

async function createLearngoals() {
    await sql`
        CREATE TABLE IF NOT EXISTS learngoal
        (
            id      UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
            user_id UUID         NOT NULL,
            lsub_id INTEGER      NOT NULL,
            label   VARCHAR(255) NOT NULL,
            status  TEXT DEFAULT 'planned',

            CONSTRAINT fk_learngoal_user
                FOREIGN KEY (user_id)
                    REFERENCES users (id),

            CONSTRAINT fk_learngoal_learnsubject
                FOREIGN KEY (lsub_id)
                    REFERENCES learnsubject (id)
        );
    `;
}

async function createLearnSessions() {
    await sql`
        CREATE TABLE IF NOT EXISTS learnsession
        (
            id         UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
            user_id    UUID      NOT NULL,
            lg_id      UUID      NOT NULL,
            start_time TIMESTAMP NOT NULL,
            end_time   TIMESTAMP,

            CONSTRAINT fk_learnsession_user
                FOREIGN KEY (user_id)
                    REFERENCES users (id),

            CONSTRAINT fk_learnsession_learngoal
                FOREIGN KEY (lg_id)
                    REFERENCES learngoal (id)
        );
    `;
}

// ==========================
// JUNCTION TABLES
// ==========================

async function createFrameworksDevCategories() {
    await sql`
        CREATE TABLE IF NOT EXISTS framework_dev_category
        (
            fw_id  INTEGER NOT NULL,
            cat_id INTEGER NOT NULL,

            CONSTRAINT pk_framework_dev_category
                PRIMARY KEY (fw_id, cat_id),

            CONSTRAINT fk_framework_dev_category_framework
                FOREIGN KEY (fw_id)
                    REFERENCES framework (id),

            CONSTRAINT fk_framework_dev_category_dev_category
                FOREIGN KEY (cat_id)
                    REFERENCES dev_category (id)
        );
    `;
}

async function createLanguagesDevCategories() {
    await sql`
        CREATE TABLE IF NOT EXISTS language_dev_category
        (
            l_id   INTEGER NOT NULL,
            cat_id INTEGER NOT NULL,

            CONSTRAINT pk_language_dev_category
                PRIMARY KEY (l_id, cat_id),

            CONSTRAINT fk_language_dev_category_language
                FOREIGN KEY (l_id)
                    REFERENCES language (id),

            CONSTRAINT fk_language_dev_category_dev_category
                FOREIGN KEY (cat_id)
                    REFERENCES dev_category (id)
        );
    `;
}

async function createFrameworksProjects() {
    await sql`
        CREATE TABLE IF NOT EXISTS framework_project
        (
            fw_id INTEGER NOT NULL,
            p_id  UUID    NOT NULL,

            CONSTRAINT pk_framework_project
                PRIMARY KEY (fw_id, p_id),

            CONSTRAINT fk_framework_project_framework
                FOREIGN KEY (fw_id)
                    REFERENCES framework (id),

            CONSTRAINT fk_framework_project_project
                FOREIGN KEY (p_id)
                    REFERENCES project (id)
        );
    `;
}

async function createLanguagesProjects() {
    await sql`
        CREATE TABLE IF NOT EXISTS language_project
        (
            l_id INTEGER NOT NULL,
            p_id UUID    NOT NULL,

            CONSTRAINT pk_language_project
                PRIMARY KEY (l_id, p_id),

            CONSTRAINT fk_language_project_language
                FOREIGN KEY (l_id)
                    REFERENCES language (id),

            CONSTRAINT fk_language_project_project
                FOREIGN KEY (p_id)
                    REFERENCES project (id)
        );
    `;
}

async function createLearngoalsLanguages() {
    await sql`
        CREATE TABLE IF NOT EXISTS learngoal_language
        (
            lg_id UUID    NOT NULL,
            l_id  INTEGER NOT NULL,

            CONSTRAINT pk_learngoal_language
                PRIMARY KEY (lg_id, l_id),

            CONSTRAINT fk_learngoal_language_learngoal
                FOREIGN KEY (lg_id)
                    REFERENCES learngoal (id),

            CONSTRAINT fk_learngoal_language_language
                FOREIGN KEY (l_id)
                    REFERENCES language (id)
        );
    `;
}

async function createLearngoalsFrameworks() {
    await sql`
        CREATE TABLE IF NOT EXISTS learngoal_framework
        (
            lg_id UUID    NOT NULL,
            fw_id INTEGER NOT NULL,

            CONSTRAINT pk_learngoal_framework
                PRIMARY KEY (lg_id, fw_id),

            CONSTRAINT fk_learngoal_framework_learngoal
                FOREIGN KEY (lg_id)
                    REFERENCES learngoal (id),

            CONSTRAINT fk_learngoal_framework_framework
                FOREIGN KEY (fw_id)
                    REFERENCES framework (id)
        );
    `;
}

export async function createTables() {
        await createUsers();
        await createCertificates();
        await createProjects();
        await createDevCategories();
        await createFrameworks();
        await createLanguages();
        await createLearnsubjects();
        await createLearngoals();
        await createLearnSessions();

        // Junction Tables
        await createFrameworksDevCategories();
        await createLanguagesDevCategories();
        await createFrameworksProjects();
        await createLanguagesProjects();
        await createLearngoalsLanguages();
        await createLearngoalsFrameworks();
}