CREATE TABLE "account" (
	"id" text PRIMARY KEY,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL UNIQUE,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY,
	"name" text NOT NULL,
	"email" text NOT NULL UNIQUE,
	"email_verified" boolean DEFAULT false NOT NULL,
	"role" text DEFAULT 'user' NOT NULL,
	"image" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "certificate" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"user_id" text NOT NULL,
	"label" varchar(100) NOT NULL,
	"date" date NOT NULL
);
--> statement-breakpoint
CREATE TABLE "learning_goal" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"user_id" text NOT NULL,
	"learning_subject_id" integer,
	"label" varchar(255) NOT NULL,
	"status" text DEFAULT 'planned'
);
--> statement-breakpoint
CREATE TABLE "learning_goal_framework" (
	"learning_goal_id" uuid,
	"framework_id" integer,
	CONSTRAINT "learning_goal_framework_pkey" PRIMARY KEY("learning_goal_id","framework_id")
);
--> statement-breakpoint
CREATE TABLE "learning_goal_language" (
	"learning_goal_id" uuid,
	"language_id" integer,
	CONSTRAINT "learning_goal_language_pkey" PRIMARY KEY("learning_goal_id","language_id")
);
--> statement-breakpoint
CREATE TABLE "learning_session" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"user_id" text NOT NULL,
	"learning_goal_id" uuid NOT NULL,
	"start_time" timestamp DEFAULT now() NOT NULL,
	"end_time" timestamp
);
--> statement-breakpoint
CREATE TABLE "learning_subject" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "learning_subject_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"label" varchar(100) NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE TABLE "framework_project" (
	"framework_id" integer,
	"project_id" uuid,
	CONSTRAINT "framework_project_pkey" PRIMARY KEY("framework_id","project_id")
);
--> statement-breakpoint
CREATE TABLE "language_project" (
	"language_id" integer,
	"project_id" uuid,
	CONSTRAINT "language_project_pkey" PRIMARY KEY("language_id","project_id")
);
--> statement-breakpoint
CREATE TABLE "project" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"user_id" text NOT NULL,
	"label" varchar(100) NOT NULL,
	"description" text,
	"start_date" date DEFAULT now() NOT NULL,
	"end_date" date
);
--> statement-breakpoint
CREATE TABLE "development_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "development_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"label" varchar(100) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "framework" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "framework_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"label" varchar(100) NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE TABLE "framework_development_category" (
	"framework_id" integer,
	"development_category_id" integer,
	CONSTRAINT "framework_development_category_pkey" PRIMARY KEY("framework_id","development_category_id")
);
--> statement-breakpoint
CREATE TABLE "language" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "language_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"label" varchar(100) NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE TABLE "language_development_category" (
	"language_id" integer,
	"developmnet_category_id" integer,
	CONSTRAINT "language_development_category_pkey" PRIMARY KEY("language_id","developmnet_category_id")
);
--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "account" ("user_id");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "session" ("user_id");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" ("identifier");--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "certificate" ADD CONSTRAINT "certificate_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "learning_goal" ADD CONSTRAINT "learning_goal_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "learning_goal" ADD CONSTRAINT "learning_goal_learning_subject_id_learning_subject_id_fkey" FOREIGN KEY ("learning_subject_id") REFERENCES "learning_subject"("id");--> statement-breakpoint
ALTER TABLE "learning_goal_framework" ADD CONSTRAINT "learning_goal_framework_learning_goal_id_learning_goal_id_fkey" FOREIGN KEY ("learning_goal_id") REFERENCES "learning_goal"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "learning_goal_framework" ADD CONSTRAINT "learning_goal_framework_framework_id_framework_id_fkey" FOREIGN KEY ("framework_id") REFERENCES "framework"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "learning_goal_language" ADD CONSTRAINT "learning_goal_language_learning_goal_id_learning_goal_id_fkey" FOREIGN KEY ("learning_goal_id") REFERENCES "learning_goal"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "learning_goal_language" ADD CONSTRAINT "learning_goal_language_language_id_language_id_fkey" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "learning_session" ADD CONSTRAINT "learning_session_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "learning_session" ADD CONSTRAINT "learning_session_learning_goal_id_learning_goal_id_fkey" FOREIGN KEY ("learning_goal_id") REFERENCES "learning_goal"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "framework_project" ADD CONSTRAINT "framework_project_framework_id_framework_id_fkey" FOREIGN KEY ("framework_id") REFERENCES "framework"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "framework_project" ADD CONSTRAINT "framework_project_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "language_project" ADD CONSTRAINT "language_project_language_id_language_id_fkey" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "language_project" ADD CONSTRAINT "language_project_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "project" ADD CONSTRAINT "project_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "framework_development_category" ADD CONSTRAINT "framework_development_category_framework_id_framework_id_fkey" FOREIGN KEY ("framework_id") REFERENCES "framework"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "framework_development_category" ADD CONSTRAINT "framework_development_category_LF0PCLhpEfCJ_fkey" FOREIGN KEY ("development_category_id") REFERENCES "development_category"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "language_development_category" ADD CONSTRAINT "language_development_category_language_id_language_id_fkey" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "language_development_category" ADD CONSTRAINT "language_development_category_d5BuxsgGhLeP_fkey" FOREIGN KEY ("developmnet_category_id") REFERENCES "development_category"("id") ON DELETE CASCADE;